export const CollegesData = [
    {
      title: "Indian Institute Of Science (IISc) Bangalore ",
      role:   "Role: Graduate Trainee Engineer",
      salary:   "Salary: 15.6 LPA",
      hiringDate:   "Hiring Date: 01-06-2022",
      joiningDate:   "Joining Date: 22-06-2023",
    },
    {
        title: "Indian Institute Of Science (IISc) Bangalore",
        role:   "Role: Associate Engineer",
        salary:   "Salary: 11.6 LPA",
        hiringDate:   "Hiring Date: 01-06-2022",
      joiningDate:   "Joining Date: 22-06-2023",
      },
      {
        title: "Indian Institute Of Science (IISc) Bangalore",
        role:   "Role: Software Development Engineer",
        salary:   "Salary: 10.4 LPA",
        hiringDate:   "Hiring Date: 01-06-2022",
      joiningDate:   "Joining Date: 22-06-2023",
      },
      {
        title: "Indian Institute Of Science (IISc) Bangalore",
        role:   "Role: Graduate Analyst",
        salary:   "Salary: 9.6 LPA",
        hiringDate:   "Hiring Date: 01-06-2022",
      joiningDate:   "Joining Date: 22-06-2023",
      },
      {
        title: "Indian Institute Of Science (IISc) Bangalore ",
        role:   "Role: Graduate Trainee Engineer",
        salary:   "Salary: 15.6 LPA",
        hiringDate:   "Hiring Date: 01-06-2022",
        joiningDate:   "Joining Date: 22-06-2023",
      },
      {
          title: "Indian Institute Of Science (IISc) Bangalore",
          role:   "Role: Associate Engineer",
          salary:   "Salary: 11.6 LPA",
          hiringDate:   "Hiring Date: 01-06-2022",
        joiningDate:   "Joining Date: 22-06-2023",
        },
        {
          title: "Indian Institute Of Science (IISc) Bangalore",
          role:   "Role: Software Development Engineer",
          salary:   "Salary: 10.4 LPA",
          hiringDate:   "Hiring Date: 01-06-2022",
        joiningDate:   "Joining Date: 22-06-2023",
        },
        {
          title: "Indian Institute Of Science (IISc) Bangalore",
          role:   "Role: Graduate Analyst",
          salary:   "Salary: 9.6 LPA",
          hiringDate:   "Hiring Date: 01-06-2022",
        joiningDate:   "Joining Date: 22-06-2023",
        },
        {
          title: "Indian Institute Of Science (IISc) Bangalore ",
          role:   "Role: Graduate Trainee Engineer",
          salary:   "Salary: 15.6 LPA",
          hiringDate:   "Hiring Date: 01-06-2022",
          joiningDate:   "Joining Date: 22-06-2023",
        },
        {
            title: "Indian Institute Of Science (IISc) Bangalore",
            role:   "Role: Associate Engineer",
            salary:   "Salary: 11.6 LPA",
            hiringDate:   "Hiring Date: 01-06-2022",
          joiningDate:   "Joining Date: 22-06-2023",
          },
          {
            title: "Indian Institute Of Science (IISc) Bangalore",
            role:   "Role: Software Development Engineer",
            salary:   "Salary: 10.4 LPA",
            hiringDate:   "Hiring Date: 01-06-2022",
          joiningDate:   "Joining Date: 22-06-2023",
          },
          {
            title: "Indian Institute Of Science (IISc) Bangalore",
            role:   "Role: Graduate Analyst",
            salary:   "Salary: 9.6 LPA",
            hiringDate:   "Hiring Date: 01-06-2022",
          joiningDate:   "Joining Date: 22-06-2023",
          },
          {
            title: "Indian Institute Of Science (IISc) Bangalore ",
            role:   "Role: Graduate Trainee Engineer",
            salary:   "Salary: 15.6 LPA",
            hiringDate:   "Hiring Date: 01-06-2022",
            joiningDate:   "Joining Date: 22-06-2023",
          },
          {
              title: "Indian Institute Of Science (IISc) Bangalore",
              role:   "Role: Associate Engineer",
              salary:   "Salary: 11.6 LPA",
              hiringDate:   "Hiring Date: 01-06-2022",
            joiningDate:   "Joining Date: 22-06-2023",
            },
            {
              title: "Indian Institute Of Science (IISc) Bangalore",
              role:   "Role: Software Development Engineer",
              salary:   "Salary: 10.4 LPA",
              hiringDate:   "Hiring Date: 01-06-2022",
            joiningDate:   "Joining Date: 22-06-2023",
            },
            {
              title: "Indian Institute Of Science (IISc) Bangalore",
              role:   "Role: Graduate Analyst",
              salary:   "Salary: 9.6 LPA",
              hiringDate:   "Hiring Date: 01-06-2022",
            joiningDate:   "Joining Date: 22-06-2023",
            },
  ];
  