export const EmployeeData = [
      {
        name: "Nikhil Dethe",
        email: "nbd@example.com",
        role: "Project Manager",
        gender: "Female",
        salary: "80000",
        empid: "1",
        experience: "20 years",
        },
      {
        name: "Amit Shinde",
        email: "ams@example.com",
        role: "Software Engineer",
        gender: "Male",
        salary: "102000",
        empid: "2",
        experience: "30 years",
        },
      {
        name: "Siddhart Nigade",
        email: "ssn@example.com",
        role: "Senior Developer",
        gender: "Female",
        salary: "70000",
        empid: "3",
        experience: "25 years",
       },
      {
        name: "Ganesh Chormale",
        email: "ganu@example.com",
        role: "Devops Engineer",
        gender: "Male",
        salary: "90000",
        empid: "4",
        experience: "35 years",
       },
       {
        name: "Nikhil Dethe",
        email: "nbd@example.com",
        role: "Project Manager",
        gender: "Female",
        salary: "80000",
        empid: "1",
        experience: "20 years",
        },
      {
        name: "Amit Shinde",
        email: "ams@example.com",
        role: "Software Engineer",
        gender: "Male",
        salary: "102000",
        empid: "2",
        experience: "30 years",
        },
      {
        name: "Siddhart Nigade",
        email: "ssn@example.com",
        role: "Senior Developer",
        gender: "Female",
        salary: "70000",
        empid: "3",
        experience: "25 years",
       },
      {
        name: "Ganesh Chormale",
        email: "ganu@example.com",
        role: "Devops Engineer",
        gender: "Male",
        salary: "90000",
        empid: "4",
        experience: "35 years",
       },
       {
        name: "Nikhil Dethe",
        email: "nbd@example.com",
        role: "Project Manager",
        gender: "Female",
        salary: "80000",
        empid: "1",
        experience: "20 years",
        },
      {
        name: "Amit Shinde",
        email: "ams@example.com",
        role: "Software Engineer",
        gender: "Male",
        salary: "102000",
        empid: "2",
        experience: "30 years",
        },
      {
        name: "Siddhart Nigade",
        email: "ssn@example.com",
        role: "Senior Developer",
        gender: "Female",
        salary: "70000",
        empid: "3",
        experience: "25 years",
       },
      {
        name: "Ganesh Chormale",
        email: "ganu@example.com",
        role: "Devops Engineer",
        gender: "Male",
        salary: "90000",
        empid: "4",
        experience: "35 years",
       },
       {
        name: "Nikhil Dethe",
        email: "nbd@example.com",
        role: "Project Manager",
        gender: "Female",
        salary: "80000",
        empid: "1",
        experience: "20 years",
        },
      {
        name: "Amit Shinde",
        email: "ams@example.com",
        role: "Software Engineer",
        gender: "Male",
        salary: "102000",
        empid: "2",
        experience: "30 years",
        },
      {
        name: "Siddhart Nigade",
        email: "ssn@example.com",
        role: "Senior Developer",
        gender: "Female",
        salary: "70000",
        empid: "3",
        experience: "25 years",
       },
      {
        name: "Ganesh Chormale",
        email: "ganu@example.com",
        role: "Devops Engineer",
        gender: "Male",
        salary: "90000",
        empid: "4",
        experience: "35 years",
       },
       {
        name: "Nikhil Dethe",
        email: "nbd@example.com",
        role: "Project Manager",
        gender: "Female",
        salary: "80000",
        empid: "1",
        experience: "20 years",
        },
      {
        name: "Amit Shinde",
        email: "ams@example.com",
        role: "Software Engineer",
        gender: "Male",
        salary: "102000",
        empid: "2",
        experience: "30 years",
        },
      {
        name: "Siddhart Nigade",
        email: "ssn@example.com",
        role: "Senior Developer",
        gender: "Female",
        salary: "70000",
        empid: "3",
        experience: "25 years",
       },
      {
        name: "Ganesh Chormale",
        email: "ganu@example.com",
        role: "Devops Engineer",
        gender: "Male",
        salary: "90000",
        empid: "4",
        experience: "35 years",
       },{
        name: "Nikhil Dethe",
        email: "nbd@example.com",
        role: "Project Manager",
        gender: "Female",
        salary: "80000",
        empid: "1",
        experience: "20 years",
        },
      {
        name: "Amit Shinde",
        email: "ams@example.com",
        role: "Software Engineer",
        gender: "Male",
        salary: "102000",
        empid: "2",
        experience: "30 years",
        },
      {
        name: "Siddhart Nigade",
        email: "ssn@example.com",
        role: "Senior Developer",
        gender: "Female",
        salary: "70000",
        empid: "3",
        experience: "25 years",
       },
      {
        name: "Ganesh Chormale",
        email: "ganu@example.com",
        role: "Devops Engineer",
        gender: "Male",
        salary: "90000",
        empid: "4",
        experience: "35 years",
       },
  ];
  