export const RetentionData = [

    {
        Age: 41,
        DistanceFromHome: 1,
        EnvironmentSatisfaction: 2,
        Gender: 1,
        HourlyRate: 94,
        JobInvolvement: 3,
        JobLevel: 2,
        JobSatisfaction: 4,
        MonthlyIncome: 5993,
        NumCompaniesWorked: 8,
        OverTime: 1,
        PercentSalaryHike: 11,
        PerformanceRating: 3,
        RelationshipSatisfaction: 1,
        StockOptionLevel: 0,
        TotalWorkingYears: 8,
        TrainingTimesLastYear: 0,
        WorkLifeBalance: 1,
        YearsAtCompany: 6,
        YearsInCurrentRole: 4,
        YearsSinceLastPromotion: 0,
        YearsWithCurrManager: 5,
        AVG_POS: 0,
        AVG_NEG: 0,
        BusinessTravel_Non_Travel: 0,
        BusinessTravel_Travel_Frequently: 0,
        BusinessTravel_Travel_Rarely: 1,
        MaritalStatus_Divorced: 0,
        MaritalStatus_Married: 0,
        MaritalStatus_Single: 1,
        JobRole_AESP: 0,
        JobRole_Corporate: 0,
        JobRole_Director: 0,
        JobRole_ESP: 0,
        JobRole_Manager: 0,
        JobRole_Sales: 1,
        employeeId: 1,
        name: "Lynnell Bellow",
        jobRole: "Senior Developer",
        location: "Eslöv",
        department: "Research and Development",
        cur_leaves: 52,
        risk: "high",
        email : "lynnellbellow12@gmail.com",
        contact : "7545784585"
    },
    {
        Age: 39,
        DistanceFromHome: 1,
        EnvironmentSatisfaction: 2,
        Gender: 1,
        HourlyRate: 94,
        JobInvolvement: 3,
        JobLevel: 2,
        JobSatisfaction: 4,
        MonthlyIncome: 5993,
        NumCompaniesWorked: 8,
        OverTime: 1,
        PercentSalaryHike: 11,
        PerformanceRating: 3,
        RelationshipSatisfaction: 1,
        StockOptionLevel: 0,
        TotalWorkingYears: 8,
        TrainingTimesLastYear: 0,
        WorkLifeBalance: 1,
        YearsAtCompany: 6,
        YearsInCurrentRole: 4,
        YearsSinceLastPromotion: 0,
        YearsWithCurrManager: 5,
        AVG_POS: 0,
        AVG_NEG: 0,
        BusinessTravel_Non_Travel: 0,
        BusinessTravel_Travel_Frequently: 0,
        BusinessTravel_Travel_Rarely: 1,
        MaritalStatus_Divorced: 0,
        MaritalStatus_Married: 0,
        MaritalStatus_Single: 1,
        JobRole_AESP: 0,
        JobRole_Corporate: 0,
        JobRole_Director: 0,
        JobRole_ESP: 0,
        JobRole_Manager: 0,
        JobRole_Sales: 1,
        employeeId: 2,
        name: "Kiah Godart",
        jobRole: "Senior Developer",
        location: "Eslöv",
        department: "Research and Development",
        cur_leaves: 52,
        risk: "high",
        email : "kiahgodart56@gmail.com",
        contact : "9858949485"
    },
    {
        Age: 35,
        DistanceFromHome: 1,
        EnvironmentSatisfaction: 2,
        Gender: 1,
        HourlyRate: 94,
        JobInvolvement: 3,
        JobLevel: 2,
        JobSatisfaction: 4,
        MonthlyIncome: 5993,
        NumCompaniesWorked: 8,
        OverTime: 1,
        PercentSalaryHike: 11,
        PerformanceRating: 3,
        RelationshipSatisfaction: 1,
        StockOptionLevel: 0,
        TotalWorkingYears: 8,
        TrainingTimesLastYear: 0,
        WorkLifeBalance: 1,
        YearsAtCompany: 6,
        YearsInCurrentRole: 4,
        YearsSinceLastPromotion: 0,
        YearsWithCurrManager: 5,
        AVG_POS: 0,
        AVG_NEG: 0,
        BusinessTravel_Non_Travel: 0,
        BusinessTravel_Travel_Frequently: 0,
        BusinessTravel_Travel_Rarely: 1,
        MaritalStatus_Divorced: 0,
        MaritalStatus_Married: 0,
        MaritalStatus_Single: 1,
        JobRole_AESP: 0,
        JobRole_Corporate: 0,
        JobRole_Director: 0,
        JobRole_ESP: 0,
        JobRole_Manager: 0,
        JobRole_Sales: 1,
        employeeId: 3,
        name: "Ulrick Scurrell",
        jobRole: "Senior Developer",
        location: "Eslöv",
        department: "Research and Development",
        cur_leaves: 52,
        risk: "high",
        email : "ulrickscurrell90@gmail.com",
        contact : "8588584858"
    },
    {
        Age: 30,
        DistanceFromHome: 1,
        EnvironmentSatisfaction: 2,
        Gender: 1,
        HourlyRate: 94,
        JobInvolvement: 3,
        JobLevel: 2,
        JobSatisfaction: 4,
        MonthlyIncome: 5993,
        NumCompaniesWorked: 8,
        OverTime: 1,
        PercentSalaryHike: 11,
        PerformanceRating: 3,
        RelationshipSatisfaction: 1,
        StockOptionLevel: 0,
        TotalWorkingYears: 8,
        TrainingTimesLastYear: 0,
        WorkLifeBalance: 1,
        YearsAtCompany: 6,
        YearsInCurrentRole: 4,
        YearsSinceLastPromotion: 0,
        YearsWithCurrManager: 5,
        AVG_POS: 0,
        AVG_NEG: 0,
        BusinessTravel_Non_Travel: 0,
        BusinessTravel_Travel_Frequently: 0,
        BusinessTravel_Travel_Rarely: 1,
        MaritalStatus_Divorced: 0,
        MaritalStatus_Married: 0,
        MaritalStatus_Single: 1,
        JobRole_AESP: 0,
        JobRole_Corporate: 0,
        JobRole_Director: 0,
        JobRole_ESP: 0,
        JobRole_Manager: 0,
        JobRole_Sales: 1,
        employeeId: 4,
        name: "Marylin Dovidaitis",
        jobRole: "Senior Developer",
        location: "Eslöv",
        department: "Research and Development",
        cur_leaves: 52,
        risk: "high",
        email : "marylindovidaitis@gmail.com",
        contact : "5858586868"
    },
    

]